micronaut:
  application:
    name: carrosGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/carros
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
